// packages/vue/src/formItem/formItem.vue
<template>
  <template v-if='props.name'>
    <FormItemBase v-bind='props as FormItemProps'>
      <template v-for="(_, name) in slots" #[name]="slotProps">
        <slot :name="name" v-bind="slotProps"></slot>
      </template>
    </FormItemBase>
  </template>
  <template v-else>
    <LayoutFormItem :label='props.label' :errorLayout='props.errorLayout' :labelMode='props.labelMode'
      :onlyRuleStyle='props.onlyRuleStyle' :showColon='props.showColon' :colSpan='props.colSpan'
      :rowSpan='props.rowSpan' :style='props.style' :class='props.class' :labelStyle='props.labelStyle'
      :labelClass='props.labelClass'>
      <template v-for="(_, name) in slots" #[name]="slotProps">
        <slot :name="name" v-bind="slotProps"></slot>
      </template>
    </LayoutFormItem>
  </template>
</template>

<script lang="ts" setup>
import { defineProps, withDefaults } from "vue"
import type { FormItemProps } from "../interface/index"
import LayoutFormItem from "../layout/layout.formItem.vue";
import FormItemBase from "./form.Item.base.vue"
defineOptions({
  name: 'FormItem',
  inheritAttrs: false, // 可选，防止属性自动应用到根元素
});
const props = withDefaults(defineProps<Partial<FormItemProps>>(), {
})
const slots = defineSlots<{
  default: (params: any) => any,
  label: (params: any) => any,
  helpText: (params: any) => any,
  extra: (params: any) => any,
}>()
</script>

// packages/react/src/formItem/index.tsx
import { LayoutFormItem, LayoutFormItemProps } from './../layout/layout.formItem';
import { useFormItemAttr, FormItemAttrOptions } from '../hooks/attr/attr.FormItem';
import React, { Fragment } from 'react';
import { useRegisterFormHideItem, FormItemParentNameProvider } from '@carefrees/form-utils-react-hooks';

export interface FormItemProps extends FormItemAttrOptions, LayoutFormItemProps {
  /**不进行样式渲染*/
  noStyle?: boolean;
}

/**表单项基础实例*/
const FormItemInstance = React.memo((props: FormItemProps) => {
  const {
    labelMode,
    noStyle,
    onlyRuleStyle,
    label,
    helpText,
    extra,
    errorLayout,
    required,
    showColon,
    colSpan,
    rowSpan,
    ...rest
  } = props;
  const { children, ruleInstance, formItemInstance, htmlFor, validateResult } = useFormItemAttr({ ...rest });
  if (noStyle) {
    return (
      <FormItemParentNameProvider name={formItemInstance.name} sort={formItemInstance.sort}>
        {children}
      </FormItemParentNameProvider>
    );
  }
  return (
    <FormItemParentNameProvider name={formItemInstance.name} sort={formItemInstance.sort}>
      <LayoutFormItem
        labelMode={labelMode}
        onlyRuleStyle={onlyRuleStyle}
        required={required || ruleInstance?.isRequired?.()}
        label={label}
        helpText={helpText}
        extra={extra}
        errorLayout={errorLayout}
        showColon={showColon}
        colSpan={colSpan}
        rowSpan={rowSpan}
        htmlFor={htmlFor}
        validateResult={validateResult}
      >
        {children}
      </LayoutFormItem>
    </FormItemParentNameProvider>
  );
});

/**表单项*/
export const FormItem = React.memo((props: Partial<FormItemProps>) => {
  const { name } = props;
  if (name) {
    return <FormItemInstance {...props} name={name} />;
  }
  const {
    labelMode,
    onlyRuleStyle,
    label,
    helpText,
    extra,
    errorLayout,
    required,
    showColon,
    colSpan,
    rowSpan,
    children,
  } = props;
  return (
    <LayoutFormItem
      labelMode={labelMode}
      onlyRuleStyle={onlyRuleStyle}
      required={required}
      label={label}
      helpText={helpText}
      extra={extra}
      errorLayout={errorLayout}
      showColon={showColon}
      colSpan={colSpan}
      rowSpan={rowSpan}
    >
      {children}
    </LayoutFormItem>
  );
});

/**隐藏表单项*/
export const FormHideItem = React.memo((props: FormItemProps) => {
  const { name, sort, isJoinParentField } = props;
  const { isHide } = useRegisterFormHideItem({ name, sort: sort, isJoinParentField });
  if (isHide) {
    return <Fragment />;
  }
  return <FormItemInstance {...props} />;
});
