// packages/react/src/layout/index.tsx
import React, { Fragment, useMemo, useRef } from 'react';
import clx from 'classnames';
import { AttrsOptions, AttrsContext, useAttrs } from '@carefrees/form-utils-react-hooks';
import { FormLayoutBody, FormLayoutBodyProps } from './layout.body';
export interface FormLayoutProps extends AttrsOptions, FormLayoutBodyProps {
  /**标题*/
  title?: React.ReactNode;
  /**额外内容*/
  extra?: React.ReactNode;
  /**内容*/
  children?: React.ReactNode;
  /**是否占据整行*/
  isAllColSpan?: boolean;
  className?: string;
  /**头部ClassName*/
  headerClassName?: string;
  /**内容ClassName*/
  bodyClassName?: string;
  style?: React.CSSProperties;
  /**头部样式*/
  headerStyle?: React.CSSProperties;
  /**内容样式*/
  bodyStyle?: React.CSSProperties;
  /**是否添加边框*/
  bordered?: boolean;
}

const preCls = 'carefrees-form-layout';

/**布局组件*/
export const FormLayout = React.memo((props: FormLayoutProps) => {
  const {
    colCount: p_colCount = 4,
    errorLayout: p_errorLayout = 'left-bottom',
    labelMode: p_labelMode = 'left',
    showColon: p_showColon = true,
    formItemClassName: p_formItemClassName,
    formItemStyle: p_formItemStyle,
    formItemLabelClassName: p_formItemLabelClassName,
    formItemLabelStyle: p_formItemLabelStyle,
  } = useAttrs();
  const {
    colCount = p_colCount,
    title,
    extra,
    children,
    isAllColSpan,
    className,
    headerClassName,
    bodyClassName,
    style,
    headerStyle,
    bodyStyle,
    errorLayout = p_errorLayout,
    labelMode = p_labelMode,
    showColon = p_showColon,
    formItemClassName = p_formItemClassName,
    formItemStyle = p_formItemStyle,
    formItemLabelClassName = p_formItemLabelClassName,
    formItemLabelStyle = p_formItemLabelStyle,
    bordered = false,
    gap,
    onResize,
    onGapRow,
  } = props;
  const propsRef = useRef(props);
  propsRef.current = props;

  const bodyCls = useMemo(() => clx(`${preCls}-body`, bodyClassName), [bodyClassName]);
  const headerCls = useMemo(() => clx(`${preCls}-header`, headerClassName), [headerClassName]);
  const headerTitleCls = useMemo(() => clx(`${preCls}-header-title`), []);
  const headerExtraCls = useMemo(() => clx(`${preCls}-header-extra`), []);

  const cls = useMemo(
    () =>
      clx(preCls, className, {
        'all-colspan': isAllColSpan,
        bordered: bordered,
      }),
    [className],
  );

  const value = useMemo(() => {
    return {
      colCount,
      errorLayout,
      labelMode,
      showColon,
      formItemClassName,
      formItemStyle,
      formItemLabelClassName,
      formItemLabelStyle,
    };
  }, [
    colCount,
    errorLayout,
    labelMode,
    showColon,
    formItemClassName,
    formItemStyle,
    formItemLabelClassName,
    formItemLabelStyle,
  ]);

  return (
    <AttrsContext.Provider value={value}>
      <div style={style} className={cls}>
        {title || extra ? (
          <div style={headerStyle} className={headerCls}>
            <div className={headerTitleCls}>{title}</div>
            <div className={headerExtraCls}>{extra}</div>
          </div>
        ) : (
          <Fragment />
        )}
        <FormLayoutBody
          onResize={onResize}
          onGapRow={onGapRow}
          gap={gap}
          style={bodyStyle}
          className={bodyCls}
          colCount={colCount}
        >
          {children}
        </FormLayoutBody>
      </div>
    </AttrsContext.Provider>
  );
});

export interface FormLayoutRowsProps
  extends React.DetailedHTMLProps<React.HTMLAttributes<HTMLDivElement>, HTMLDivElement> {}

/**布局组件 占据一整行*/
export const FormLayoutRows = React.forwardRef<HTMLDivElement, FormLayoutRowsProps>((props, ref) => {
  const cls = useMemo(
    () =>
      clx(preCls, props.className, {
        'all-colspan': true,
      }),
    [props.className],
  );
  return <div {...props} ref={ref} className={cls} />;
});

// packages/vue/src/layout/layout.vue
<template>
  <div :style='props.style' :class='cls'>
    <template v-if="isExtra || isTitle">
      <div :style='headerStyle' :class='headerCls'>
        <div :class='headerTitleCls'>
          <template v-if='props.title'>
            {{ props.title }}
          </template>
          <template v-else>
            <slot name='title' />
          </template>
        </div>
        <div :class='headerExtraCls'>
          <template v-if='props.extra'>
            {{ props.extra }}
          </template>
          <template v-else>
            <slot name='extra' />
          </template>
        </div>
      </div>
    </template>
    <div :style='bodyStyle' :class='bodyCls'>
      <slot />
    </div>
  </div>
</template>

<script lang="ts" setup>
import clx from 'classnames';
import { defineProps, withDefaults, toValue, computed, StyleValue } from "vue"
import type { FormLayoutProps } from "../interface/layout"
import { useAttrsInject, useAttrsProvide } from "@carefrees/form-utils-vue-hooks"

const preCls = 'carefrees-form-layout';

const attrs = useAttrsInject();
const props = withDefaults(defineProps<FormLayoutProps>(), {})

defineOptions({
  name: 'Layout',
  inheritAttrs: false, // 可选，防止属性自动应用到根元素
});

const solts = defineSlots<{
  default: any,
  title: any,
  extra: any,
}>()

const colCount = computed(() => toValue(props.colCount) ?? toValue(attrs.value.colCount))
const errorLayout = computed(() => toValue(props.errorLayout) ?? toValue(attrs.value.errorLayout))
const labelMode = computed(() => toValue(props.labelMode) ?? toValue(attrs.value.labelMode))
const showColon = computed(() => toValue(props.showColon) ?? toValue(attrs.value.showColon))
const formItemClass = computed(() => toValue(props.formItemClass) ?? toValue(attrs.value.formItemClass))
const formItemStyle = computed(() => toValue(props.formItemStyle) ?? toValue(attrs.value.formItemStyle))
const formItemLabelClass = computed(() => toValue(props.formItemLabelClass) ?? toValue(attrs.value.formItemLabelClass))
const formItemLabelStyle = computed(() => toValue(props.formItemLabelStyle) ?? toValue(attrs.value.formItemLabelStyle))

useAttrsProvide({
  colCount,
  errorLayout,
  labelMode,
  showColon,
  formItemClass,
  formItemStyle,
  formItemLabelClass,
  formItemLabelStyle
})

const cls = computed(() => clx(preCls, props.class, { 'all-colspan': props.isAllColSpan, bordered: props.bordered, }));
const bodyCls = computed(() => clx(`${preCls}-body`, props.bodyClass));
const headerCls = computed(() => clx(`${preCls}-header`, props.headerClass));
const headerTitleCls = computed(() => clx(`${preCls}-header-title`));
const headerExtraCls = computed(() => clx(`${preCls}-header-extra`));

const bodyStyle = computed(() => {
  const css: StyleValue = {};
  if (typeof props.gap === 'string') {
    css.gap = props.gap;
  }
  if (typeof props.gap === 'number') {
    css.gap = `${props.gap}px`;
  }
  if (colCount.value) {
    css.gridTemplateColumns = `repeat(${colCount.value}, auto)`;
  }
  return [css, props.bodyStyle];
});

const isTitle = computed(() => {
  return !!props.title || solts.title;
})

const isExtra = computed(() => {
  return !!props.extra || solts.extra;
})
</script>
