// packages/vue/src/layout/layout.formItem.vue
<template>
  <div :class='cls' :style='style'>
    <div :class='containerCls'>
      <template v-if='_isLabel'>
        <div :class='labelWarpCls'>
          <label :style='labelStyle' :class='labelCls' :for='toValue(props.htmlFor)'>
            <template v-if='props.label'>
              {{ props.label }}
            </template>
            <template v-else>
              <slot name='label' />
            </template>
          </label>
        </div>
      </template>
      <div :class='preCls + "-body"'>
        <div :class='inputCls'>
          <slot />
        </div>
        <template v-if='isHelpText'>
          <div :class='preCls + "-body-help"'>
            <template v-if='props.helpText'>
              {{ props.helpText }}
            </template>
            <template v-else>
              <slot name='helpText' />
            </template>
          </div>
        </template>
        <template v-if='!!tips'>
          <div :class='errorCls'>{{ tips }}</div>
        </template>
      </div>
    </div>
    <template v-if='isExtra'>
      <div :class='preCls + "-extra"'>
        <template v-if='props.extra'>
          {{ props.extra }}
        </template>
        <template v-else>
          <slot name='extra' />
        </template>
      </div>
    </template>
  </div>
</template>

<script lang="ts" setup>
import clx from 'classnames';
import { defineProps, withDefaults, toValue, computed, StyleValue } from "vue"
import type { LayoutFormItemProps } from "../interface/layout.formItem"
import { useAttrsInject } from "../hooks/useAttrs"
const preCls = 'carefrees-form-item';
defineOptions({
  name: 'LayoutFormItem',
  inheritAttrs: false, // 可选，防止属性自动应用到根元素
});
const attrs = useAttrsInject();
const props = withDefaults(defineProps<LayoutFormItemProps>(), {})

const solts = defineSlots<{
  default: any,
  label: any,
  helpText: any,
  extra: any,
}>()

const labelMode = computed(() => props.labelMode ?? toValue(attrs.value.labelMode) ?? 'top')
const showColon = computed(() => props.showColon ?? toValue(attrs.value.showColon))
const errorLayout = computed(() => props.errorLayout ?? toValue(attrs.value.errorLayout) ?? "left-bottom")
const tips = computed(() => {
  const v = toValue(props.validateResult)?.tip
  if (Array.isArray(v)) {
    return v.join(',')
  }
  return v
});

const cls = computed(() => clx(preCls, props.class, toValue(attrs.value.formItemClass), { 'dx-invalid': !!toValue(props.validateResult)?.isInvalid }))
const containerCls = computed(() => clx(`${preCls}-container`, { [`${labelMode.value}`]: !!labelMode.value }));
const labelCls = computed(() => clx(`${preCls}-label`, { required: !!props.required, 'show-colon': showColon && (labelMode.value === 'left' || labelMode.value === 'between'), },));
const labelWarpCls = computed(() => clx(`${preCls}-label-warp`, toValue(props.labelClass), toValue(attrs.value.formItemLabelClass)));
const inputCls = computed(() => clx(`${preCls}-body-input`));
const errorCls = computed(() => clx(`${preCls}-body-error`, { [errorLayout.value]: !!errorLayout.value }));
const _isLabel = computed(() => (props.label || solts.label) && labelMode.value !== 'hide');

const style = computed(() => {
  const css: StyleValue = {};

  if (props.onlyRuleStyle) {
    css.padding = '0px';
  }

  if (props.colSpan) {
    const colCount = toValue(attrs.value.colCount) || 4;
    const end = colCount > props.colSpan ? props.colSpan : colCount;
    css.gridColumnEnd = `span ${end}`;
  }

  if (props.rowSpan) {
    css.gridRowEnd = `span ${props.rowSpan}`;
  }

  return [toValue(attrs.value.formItemStyle), props.style, css]
})

const labelStyle = computed(() => {
  return [toValue(attrs.value.formItemLabelStyle), props.labelStyle]
})

const isHelpText = computed(() => {
  return !!props.helpText || solts.helpText;
})

const isExtra = computed(() => {
  return !!props.extra || solts.extra;
})

</script>

// packages/react-native/src/layout/layout.formItem.tsx
import { View, ViewProps, Text } from 'react-native';
import React, { Fragment, useMemo, memo } from 'react';
import { useAttrs } from '../hooks/useAttrs';
import { StylesBase } from '../styles';

export interface LayoutFormItemProps {
  /**规则校验失败错误提示位置*/
  errorLayout?: 'left-bottom' | 'right-bottom' | 'top-right' | 'top-left';
  /**必填样式*/
  required?: boolean;
  /**label显示模式*/
  labelMode?: 'left' | 'top' | 'between' | 'hide';
  /**内容*/
  children?: React.ReactNode;
  /**只进行规则样式*/
  onlyRuleStyle?: boolean;
  label?: React.ReactNode;
  /**底部提示内容*/
  helpText?: React.ReactNode;
  /**额外内容*/
  extra?: React.ReactNode;
  /**是否显示label后的冒号*/
  showColon?: boolean;
  /**
   * 表单项占据列数
   * @default 1
   */
  colSpan?: number;
  /**
   * 表单项占据行数
   * @default 1
   */
  rowSpan?: number;

  htmlFor?: string;
  /**规则验证结果*/
  validateResult?: {
    tip: string | (string | undefined)[];
    isInvalid: boolean;
  };
  // 样式部分
  style?: ViewProps['style'];
  labelStyle?: ViewProps['style'];
  /**底部边框*/
  inputBordered?: boolean;
}

/**布局组件 表单项*/
export const LayoutFormItem = memo((props: LayoutFormItemProps) => {
  const {
    formItemLabelStyle,
    formItemStyle,
    labelMode: p_labelMode = 'top',
    errorLayout: p_errorLayout = 'left-bottom',
    showColon: p_showColon = true,
    colCount = 1,
    inputBordered: p_inputBordered = true,
  } = useAttrs();

  const {
    children,
    labelMode = p_labelMode,
    onlyRuleStyle,
    label,
    helpText,
    extra,
    showColon = p_showColon,
    colSpan = 1,
    validateResult,
    htmlFor,
    required,
    errorLayout = p_errorLayout,
    style,
    labelStyle,
    inputBordered = p_inputBordered,
  } = props;

  const tip = validateResult?.tip;
  const isInvalid = !!validateResult?.isInvalid;
  const _errorLayout = labelMode === 'between' ? 'right-bottom' : errorLayout;
  const _isLabel = useMemo(() => label && labelMode !== 'hide', [label, labelMode]);

  const _isShowColon = useMemo(() => {
    return showColon && (labelMode === 'left' || labelMode === 'between');
  }, [showColon, labelMode]);

  const widthStyles: ViewProps['style'] = useMemo(() => {
    if (colCount >= colSpan) {
      return {
        width: `${(100 / colCount) * colSpan}%`,
      };
    }
    return { width: `100%` };
  }, [colSpan, colCount]);

  const warpStyles = useMemo(() => {
    return [
      StylesBase['carefrees-form-item'],
      onlyRuleStyle && StylesBase['carefrees-form-item.only-rule-style'],
      widthStyles,
      formItemStyle,
      style,
    ].filter(Boolean);
  }, [style, widthStyles, onlyRuleStyle, formItemStyle]);

  const containerStyles = useMemo(() => {
    return [
      StylesBase['carefrees-form-item-container'],
      labelMode === 'left' && StylesBase['carefrees-form-item-container.left'],
      labelMode === 'between' && StylesBase['carefrees-form-item-container.between'],
    ].filter(Boolean);
  }, [labelMode]);

  const labelWarpStyles = useMemo(() => {
    return [
      StylesBase['carefrees-form-item-label-warp'],
      labelMode === 'left' && StylesBase['carefrees-form-item-label-warp.left'],
      (labelMode === 'left' || labelMode == 'between') && StylesBase['carefrees-form-item-label-warp.minHeight'],
      formItemLabelStyle,
      labelStyle,
    ].filter(Boolean);
  }, [labelMode, labelStyle, formItemLabelStyle]);

  const bodyStyles = useMemo(() => {
    return [
      StylesBase['carefrees-form-item-body'],
      labelMode === 'between' && StylesBase['carefrees-form-item-body-com.between'],
    ].filter(Boolean);
  }, [labelMode]);

  const bodyInputStyles = useMemo(() => {
    return [
      StylesBase['carefrees-form-item-body-input'],
      inputBordered && StylesBase['carefrees-form-item-body-input.input-bordered'],
      labelMode === 'between' && StylesBase['carefrees-form-item-body-com.between'],
    ].filter(Boolean);
  }, [labelMode, inputBordered]);

  const errorStyles = useMemo(() => {
    return [
      StylesBase['carefrees-form-item-body-error'],
      _errorLayout && StylesBase[`carefrees-form-item-body-error.${_errorLayout}`],
    ].filter(Boolean);
  }, [_errorLayout]);

  return (
    <View style={warpStyles}>
      <View style={containerStyles}>
        {_isLabel ? (
          <View style={labelWarpStyles}>
            {required ? (
              <View>
                <Text style={[StylesBase.fontSize14, StylesBase['carefrees-form-item-label.required']]}>*</Text>
              </View>
            ) : (
              <Fragment />
            )}
            <View style={StylesBase['carefrees-form-item-label']}>
              {typeof label === 'string' ? <Text style={StylesBase.fontSize14}>{label}</Text> : label}
            </View>
            {_isShowColon ? (
              <View style={[StylesBase['carefrees-form-item-label.show-colon']]}>
                <Text style={StylesBase.fontSize14}>:</Text>
              </View>
            ) : (
              <Fragment />
            )}
          </View>
        ) : (
          <Fragment />
        )}
        <View style={bodyStyles}>
          <View style={bodyInputStyles}>{children}</View>
          {helpText ? (
            <View style={StylesBase['carefrees-form-item-body-help']}>
              {typeof helpText === 'string' ? <Text style={StylesBase.fontSize12}>{helpText}</Text> : helpText}
            </View>
          ) : (
            <Fragment />
          )}
          {isInvalid ? (
            <View style={errorStyles}>
              <Text style={StylesBase['error-text']}>{tip}</Text>
            </View>
          ) : (
            <Fragment />
          )}
        </View>
      </View>
      {extra ? (
        <View style={StylesBase['carefrees-form-item-extra']}>
          {typeof extra === 'string' ? <Text style={StylesBase.fontSize14}>{extra}</Text> : extra}
        </View>
      ) : (
        <Fragment />
      )}
    </View>
  );
});
